<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('movies')->insert([
            [
                'movie_name' => 'Trấn thành',
                // 'movie_category_id' => '1',
                // 'cinema_id' => '1',
                // 'director_id' => '11',
                // 'actor_id' => '13',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/6672a665bf15f621375171.jpg',
                'duration' => '',
                'release_date' => now(),
                'age_limit' => '1',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Làm Giàu Với Ma',
                // 'movie_category_id' => '1',
                // 'cinema_id' => '1',
                // 'director_id' => '21',
                // 'actor_id' => '11',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66b1a047a14ac186965830.jpg',
                'duration' => '',
                'release_date' => now(),
                'age_limit' => '1',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Hai Muối',
                // 'movie_category_id' => '2',
                // 'cinema_id' => '2',
                // 'director_id' => '23',
                // 'actor_id' => '21',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66c2c56176eb2629893638.jpg',
                'duration' => '',
                'release_date' => now(),
                'age_limit' => '1',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Cám',
                // 'movie_category_id' => '12',
                // 'cinema_id' => '2',
                // 'director_id' => '24',
                // 'actor_id' => '14',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66e7ddfc73b0d564220537.jpg',
                'duration' => '122',
                'release_date' => now(),
                'age_limit' => '18',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ] ,
            [
                'movie_name' => 'Đố Anh Còng Được tôi',
                // 'movie_category_id' => '5',
                // 'cinema_id' => '3',
                // 'director_id' => '12',
                // 'actor_id' => '23',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66e140bff0068188200976.jpg',
                'duration' => '118',
                'release_date' => now(),
                'age_limit' => '18',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Minh Hôn',
                // 'movie_category_id' => '9',
                // 'cinema_id' => '3',
                // 'director_id' => '11',
                // 'actor_id' => '19',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66e668c12aa05005198863.jpg',
                'duration' => '92',
                'release_date' => now(),
                'age_limit' => '18',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Transformers Một',
                // 'movie_category_id' => '6',
                // 'cinema_id' => '4',
                // 'director_id' => '13',
                // 'actor_id' => '13',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/663458008cfa2269960147.jpg',
                'duration' => '120',
                'release_date' => now(),
                'age_limit' => '13',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Cậu Bé Cá Heo',
                // 'movie_category_id' => '16',
                // 'cinema_id' => '5',
                // 'director_id' => '13',
                // 'actor_id' => '17',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66e667a965631887716128.png',
                'duration' => '85',
                'release_date' => now(),
                'age_limit' => '1',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Kết Nối Tử Thần',
                // 'movie_category_id' => '8',
                // 'cinema_id' => '5',
                // 'director_id' => '22',
                // 'actor_id' => '8',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66ed5eadb1e5c292802354.jpg',
                'duration' => '89',
                'release_date' => now(),
                'age_limit' => '16',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'movie_name' => 'Nơi Tình Yêu Kết Thúc',
                // 'movie_category_id' => '19',
                // 'cinema_id' => '5',
                // 'director_id' => '18',
                // 'actor_id' => '9',
                'poster' => 'https://cdn.moveek.com/storage/media/cache/short/66ed5e0215766604667464.jpg',
                'duration' => '130',
                'release_date' => now(),
                'age_limit' => '16',
                'description' => '',
                'trailer' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
